package constants

// 日志模板集中管理：任何业务字段变更（如 Registration 新增字段）都必须同步修改对应模板与调用处。
const (
	LogUserRegisterStart          = "user register start"
	LogUserRegisterSuccess        = "user register success"
	LogUserRegisterFailed         = "user register failed"
	LogUserLoginSuccess           = "user login success"
	LogUserLoginFailed            = "user login failed: invalid credentials"
	LogUserProfileUpdate          = "user profile update"
	LogActivityCreateSuccess      = "activity create success"
	LogActivityCreateFailed       = "activity create failed"
	LogActivityUpdateSuccess      = "activity update success"
	LogActivityPublishSuccess     = "activity publish success"
	LogActivityEndSuccess         = "activity end success"
	LogActivityDeleteSuccess      = "activity delete success"
	LogRegistrationCreateStart    = "registration create start"
	LogRegistrationCreateSuccess  = "registration create success"
	LogRegistrationCreateFailed   = "registration create failed"
	LogRegistrationCancelSuccess  = "registration cancel success"
	LogRegistrationReviewSuccess  = "registration review success"
	LogRegistrationReviewFailed   = "registration review failed"
	LogRegistrationCheckinSuccess = "registration checkin success"
	LogRegistrationCheckinFailed  = "registration checkin failed"
	LogCheckinVoucherNotFound     = "checkin voucher not found"
	LogCheckinScanFailed          = "checkin scan failed"
	LogCheckinRateStats           = "checkin rate stats"
	LogCommentCreateSuccess       = "comment create success"
	LogCommentCreateFailed        = "comment create failed"
	LogCommentDeleteSuccess       = "comment delete success"
	LogFavoriteAddSuccess         = "favorite add success"
	LogFavoriteRemoveSuccess      = "favorite remove success"
	LogNotificationCreate         = "notification create"
	LogNotificationMarkRead       = "notification mark read"
	LogAuditWriteFailed           = "audit log write failed"
	LogUploadImageSuccess         = "upload image success"
	LogUploadImageFailed          = "upload image failed"
	LogRateLimitHit               = "rate limit hit"
)
